### ISSUE TITLE
Installation when sitting in a boat

### ISSUE THREAD

**Issue by nikitinalexx** [SanAndreasP/BetterBoat#1]
I was sitting in a boat and installed your mod. When i entered the game, there was just a shadow under me and i could do nothing. So i had to delete your mode. Get out of the boat and install the mod again.

**Comment by SanAndreasP** [comment]
So... you sit in a vanilla boat prior to installing the mod, exit the game, install this mod, start the game and re-enter the world, suddenly you sit on a black spot? Yes?

**Comment by nikitinalexx** [comment]
Yeah, that is correct. And you are unable to do anything (move or leave a boat) until you uninstall the mod.

**Comment by SanAndreasP** [comment]
not even shift-to-dismount works?

Huh, I'll see what I can do.
