### ISSUE TITLE
Crash - Serverside

### ISSUE THREAD

**Issue by DPxKnightxZero** [SanAndreasP/BetterBoat#4]
Crash Log -> https://gist.github.com/DPxKnightxZero/8c98c4f379249868dcdf

Full Log -> https://gist.github.com/DPxKnightxZero/d1efe4b42239caeae303

**Comment by SanAndreasP** [comment]
Seems like a coremod is messing up one of the methods of the mod. Sadly there's no way for me to tell you which nor can I fix this myself. All you can do is do a binyary search and figure out which mod is responsible for this.

**Comment by DPxKnightxZero** [comment]
Well wouldn't it make more sense to ask one of the 8 Core modders and see which one is possibly the culprit? Your mod is good but not good enough to remove 170 worth of mods just to figure it out.
