### ISSUE TITLE
ForgeEssentials crash with BetterBoat (and Bookshelf) when placing a boat

### ISSUE THREAD

**Issue by temdur** [SanAndreasP/BetterBoat#6]
Create a new SSP world.
Place a boat.
Crash.

After that you can restart and rejoin the testworld. The boat is still in your hands. Unplaced.

Used Mods:
BetterBoat: 1.1.0
Bookshelf:  1.0.4.187 (dependency for BB)
Forge Essentials:   1164
crashlog: http://pastebin.com/qS7SZUY5

---

It also crashed with the TechnodeFirmacraft modpack. At SMP and SSP.
The difference Betterboat is maybe modified for TFC. It depended on "sapmanpack-1.7.10-2.5.1.jar" instead.

FE without BB don't crash.
BB without FE don't crash.

MC: 1.7.10
Forge: 10.13.4.1614 (Latest)
Java 8u77

---

olee [says](https://github.com/ForgeEssentials/ForgeEssentials/issues/2065#issuecomment-211043210)

> Looks like Betterboats issue because of code patching.
> The function affected is Entity.onUpdate.

**Comment by SanAndreasP** [comment]
Since BetterBoat itself isn't a coremod, it's likely a FE issue, but I'll look into it regardless.

Also the TechnodeFirmacraft modpack seems to ship an older version of the mod, since the previous versions required my Manager Pack (sapmanpack) instead of Bookshelf.

**Comment by temdur** [comment]
Yes the problem is not new. I will contact the modpack author if the problem is solved.

**Comment by Joshwoo69** [comment]
yeah same.. happens on my end.
